# Generated by Django 5.1.6 on 2025-02-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessment_url_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='invite_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
