# Generated by Django 5.1.6 on 2025-03-02 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_assessment_accepted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('question_type', models.CharField(choices=[('FRONTEND', 'Frontend Development'), ('BACKEND', 'Backend Development'), ('DATABASE', 'Database Design')], max_length=20)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=10)),
                ('example_input', models.TextField(blank=True)),
                ('example_output', models.TextField(blank=True)),
                ('constraints', models.TextField(blank=True)),
                ('starter_code_python', models.TextField(blank=True)),
                ('starter_code_javascript', models.TextField(blank=True)),
                ('starter_code_sql', models.TextField(blank=True)),
                ('starter_code_html', models.TextField(blank=True)),
                ('starter_code_css', models.TextField(blank=True)),
                ('test_cases', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='assessment',
            name='code_language',
            field=models.CharField(blank=True, default='python', max_length=50),
        ),
        migrations.AddField(
            model_name='assessment',
            name='available_questions',
            field=models.ManyToManyField(blank=True, related_name='assessments', to='core.codingquestion'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='chosen_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chosen_assessments', to='core.codingquestion'),
        ),
    ]
