# Generated by Django 5.1.6 on 2025-03-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_assessment_evaluation_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='data_cleanup_status',
            field=models.CharField(choices=[('ACTIVE', 'Active Data'), ('MARKED_FOR_DELETION', 'Marked for Deletion'), ('ANONYMIZED', 'Data Anonymized')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='interview_decision_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='interview_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='interview_status',
            field=models.CharField(choices=[('PENDING', 'Pending Decision'), ('ACCEPTED', 'Accepted for Interview'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
