# Generated by Django 5.1.6 on 2025-03-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='source',
            field=models.CharField(choices=[('DIRECT', 'Direct Application'), ('REFERRAL', 'Referral'), ('LINKEDIN', 'LinkedIn'), ('GITHUB', 'GitHub'), ('CAREER_FAIR', 'Career Fair'), ('STACK_OVERFLOW', 'Stack Overflow'), ('OTHER', 'Other')], default='DIRECT', max_length=50),
        ),
    ]
