# Generated by Django 5.1.6 on 2025-03-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_candidate_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='source',
            field=models.CharField(choices=[('GITHUB', 'GitHub'), ('STACK_OVERFLOW', 'Stack Overflow'), ('OTHER', 'Other')], default='DIRECT', max_length=50),
        ),
    ]
