# Generated by Django 5.1.6 on 2025-03-09 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_candidate_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='source_ranking',
            new_name='source_score',
        ),
    ]
