# Generated by Django 5.1.6 on 2025-03-10 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_source_ranking_candidate_source_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='years_of_experience',
        ),
    ]
