# Generated by Django 5.1.6 on 2025-03-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_candidate_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='source',
            field=models.CharField(choices=[('GITHUB', 'GitHub'), ('STACK_OVERFLOW', 'Stack Overflow'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
